jwt:
  secretKey: vusvihvwefy8wefusboweu9wur9w4y88te8efy984tu8484

spring:
  application:
    name: api-gateway


  # API Gateway Config
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
                - Method= GET, POST
              filters:
                - StripPrefix=2
                - name: LoggingOrdersFilter
                - name: Authentication
                  args:
                    isEnabled: true
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
                - Method= GET, POST
              filters:
                - StripPrefix=2
                - name: Authentication
                - AddRequestHeader=X-Custom-Header, Fardeen
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
